Alias /zm "/usr/share/zoneminder/www"
<Directory "/usr/share/zoneminder/www">
    Options -Indexes +MultiViews +FollowSymLinks
    AllowOverride All
    <IfModule mod_authz_core.c>
       # Apache 2.4
       Require all granted
    </IfModule>
    <IfModule !mod_authz_core.c>
        # Apache 2.2
        Order deny,allow
        Allow from all
    </IfModule>
    # The code unfortunately uses short tags in many places
    php_value short_open_tag 1
</Directory>

ScriptAlias /cgi-bin/zm "/usr/lib/cgi-bin"
<Directory "/usr/lib/cgi-bin">
    AllowOverride All
    Options ExecCGI
    <IfModule mod_authz_core.c>
       # Apache 2.4
       Require all granted
    </IfModule>
    <IfModule !mod_authz_core.c>
        # Apache 2.2
        Order deny,allow
        Allow from all
    </IfModule>
</Directory>
