sudo: required
services:
  - docker

language: cpp
os:
  - linux

compiler:
  - clang
  - gcc

env:
    matrix:
      - PACK=none
      - PACK=coverage
      - OS=el DIST=7 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=ubuntu DIST=xenial PACK=deb
      - OS=debian DIST=jessie PACK=deb

matrix:
    allow_failures:
      - env: PACK=coverage
      - env: OS=el DIST=7 PACK=rpm
      - env: OS=fedora DIST=23 PACK=rpm
      - env: OS=ubuntu DIST=xenial PACK=deb
      - env: OS=debian DIST=jessie PACK=deb

    exclude:
      - env: PACK=coverage
        compiler: clang
      - env: OS=el DIST=7 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=23 PACK=rpm
        compiler: clang
      - env: OS=ubuntu DIST=xenial PACK=deb
        compiler: clang
      - env: OS=debian DIST=jessie PACK=deb
        compiler: clang

script:
  - git clone https://github.com/SteveGilvarry/build.git
  - ./build/pack/travis.sh

notifications:
  irc:
    channels:
      - chat.freenode.net#zoneminder-dev
    on_success: change
    on_failure: always
  email: true

git:
  depth: 500
