name: Create Full Release Archive

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Create archive with submodules
        run: |
          mkdir -p build

          # Archive the main repo
          git archive --format=tar --prefix=zoneminder-${{ github.ref_name }}/ HEAD | tar -x -C build

          # Archive all submodules properly
          git submodule foreach --recursive '
            mkdir -p build/zoneminder-${{ github.ref_name }}/$path &&
            git archive --format=tar HEAD | tar -x -C build/zoneminder-${{ github.ref_name }}/$path
          '

          # Create compressed tarball
          tar -czf zoneminder-${{ github.ref_name }}-full.tar.gz -C build .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: zoneminder-${{ github.ref_name }}-full.tar.gz
